language: cpp
before_install:
  - export CC="gcc-4.8 -std=gnu99"
  - export CXX="g++-4.8 -std=c++11"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/dropbox.sh
  - chmod 755 ./travis-tool.sh
  - chmod 755 ./dropbox.sh
  - ./travis-tool.sh bootstrap
  - mkdir ~/.R
  - echo -e "CC=gcc-4.8 -std=gnu99\nCXX=g++-4.8 -std=c++11\nCXXFLAGS=-g -O3\nCFLAGS=-g -O3\n" > ~/.R/Makevars
  - sudo apt-get install -qq ttf-sil-gentium ttf-sil-gentium-basic
  - sudo apt-get install -qq texinfo texlive-fonts-recommended texlive-fonts-extra ttf-inconsolata ttf-droid
  - sudo apt-get install -qq texlive-xetex texlive-latex-recommended texlive-latex-extra
script:
  - cd article
  - pdflatex RJwrapper.tex
  - pdflatex RJwrapper.tex
  - cp RJwrapper.pdf ../Rcpp11_article.pdf
  - cd ..
after_failure:
  - ./travis-tool.sh dump_logs
after_success:
  - ./dropbox.sh upload Rcpp11_article.pdf
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:    
    - ACCESS_LEVEL=sandbox
    # OAUTH_ACCESS_TOKEN
    - secure: "L2nMdP3DiFG1jMJb6x8Qi9plB3NZtovhlxe6QqZwzzI+WeZYrQJL5mJyEDJ9tkHIVS9yhmf3v8bauyes7tgd28evrac++jwQxi5TETmFoeqkcOlbmyqKY74EYXNOgSoPWf96OL6i9OhamraqHN5rzSE+8w2Q0jYPXaqGXUdvkoM="
    # OAUTH_ACCESS_TOKEN_SECRET
    - secure: "DS3lr2o3FM/E7H63F6GvpAKWgzd0cvbxokQoIybEQpps21zRMFaCkBJiRDsulQ3ItzPHp8KREoUUuRCx1W4rFiLLVV94PaiKPnVBAETUUDjxMi+tkuGiUyfJYYzf0IySPl2au1jrnk7zjq0YWRlJZ75zWLjdI66UoaSfAbYmMrI="
    # APPKEY
    - secure: "SX2wfAetBCPQAU03mK0rLDtTmBjS8IBAJxIS3gaeiwpcEBFlPCHRKWGHksG255bQ71wa2b7JD4FvZML6iEDEhBggzqEh4EBUA1Uk3Yc/pS9LCPYQYgIe1SGhPJicx8gXxtqvt652z2CW+3nclUAxaEdVxmdB6CjtF6WG8HQoZP4="
    # APPSECRET
    - secure: "OEYuTL9ylGzTKuXsjzSxoieO5IJAf2jQhVbiE7KA2iLzoODB7QeyvDX15TNWgpP20AFjRKQ9x+120kqZylAZzG0pwJqfNmkvPsktHK70N2T7a3PnDH9lLdc7OpnLx9//ym/KSqa6zhR9wYFMePVI0U0PdknPaR/irU7z8VdjRVM="
    
